apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tbc-gitops-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/dwaradwara/gitops-argocd-devops-lab.git
    targetRevision: main
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: tbc-gitops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
